version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-multas-app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: N0wIctb]|03
    ports:
      - '27018:27017'
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:  
